---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: chatbot-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: chatbot-flux
  url: https://github.com/Yas2020/EKS-Istio-Multitenant.git
