---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chatbot
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-cd/overlays/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: chatbot-source
  timeout: 3m0s
  wait: true
