apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tenanta-ns.yaml
- tenantb-ns.yaml
- ../../base
images:
- name: ghcr.io/yas2020/eks-istio-multitenant/app-ui:latest
  newName: ghcr.io/yas2020/eks-istio-multitenant/app-ui:latest # {"$imagepolicy": "flux-system:app-ui:name"}
  newTag: latest # {"$imagepolicy": "flux-system:app-ui:tag"}
- name: ghcr.io/yas2020/eks-istio-multitenant/rag-api
  newName: ghcr.io/yas2020/eks-istio-multitenant/rag-api # {"$imagepolicy": "flux-system:rag-api:name"}
  newTag: 0.0.1 # {"$imagepolicy": "flux-system:rag-api:tag"}
